version: "3.9"
services:
  database:
    image: postgres
    container_name: postgres-docker
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local